In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
mylist=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
mymatrix=np.array(mylist)

In [9]:
mymatrix.shape

(3, 3)

In [10]:
np.arrange(0,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(4,10)

TypeError: data type not understood

In [15]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.ones((5,4)) + 2

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [18]:
[1,1,1,1] *6

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.eye(4.4)

TypeError: 'float' object cannot be interpreted as an integer

In [25]:
np.random.rand(5,5)

array([[0.3282747 , 0.96442706, 0.08033398, 0.17923985, 0.71935579],
       [0.52755679, 0.45526826, 0.94102805, 0.76044482, 0.53638916],
       [0.63755349, 0.30589826, 0.77093177, 0.5400815 , 0.07675375],
       [0.95473328, 0.90985044, 0.72747692, 0.03185146, 0.38304414],
       [0.75034769, 0.0192771 , 0.85576526, 0.08105341, 0.26716897]])

In [26]:
np.random.rand(3)

array([0.12886619, 0.48761794, 0.62060752])

In [27]:
np.random.randn(10)

array([-1.49333406,  0.51457205, -1.24170421, -0.60972825,  0.76054715,
        0.59579418, -1.58071915, -0.3305393 ,  0.48907589,  0.83944931])

In [28]:
np.random.randn(1)

array([-0.8248903])

In [34]:
np.random.randint(1,100,10)

array([21, 76, 15, 97, 48, 34, 79, 39, 16, 96])

In [35]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [36]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
arr=np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr=np.random.randint(0,50,10)

In [40]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr.min()

2

In [45]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [46]:
ranarr.max()

39

In [47]:
ranarr.max()

39

In [48]:
ranarr.argmax()

7

In [49]:
ranarr.argmin()

9

In [50]:
ranarr.dtype

dtype('int32')

In [52]:
arr=np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[:5]

array([0, 1, 2, 3, 4])

In [56]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [57]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [58]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [59]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
slice_of_arr=arr[0:6]

In [65]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [66]:
slice_of_arr[:]=99

In [67]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [69]:
arr_copy=arr.copy()

In [70]:
arr_copy[:]=1000

In [71]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr_2d=np.array([[5,10,15],[20,35,30],[35,40,45]])

In [77]:
arr_2d

array([[ 5, 10, 15],
       [20, 35, 30],
       [35, 40, 45]])

In [78]:
arr_2d.shape

(3, 3)

In [79]:
arr_2d[1]

array([20, 35, 30])

In [80]:
arr_2d[1][1]

35

In [81]:
arr_2d[1,1]

35

In [83]:
arr_2d[2,1]

40

In [84]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 35, 30]])

In [85]:
arr_2d[:2,1:]

array([[10, 15],
       [35, 30]])

In [86]:
arr=np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [89]:
bool_arr=arr>4

In [90]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [91]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [92]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [93]:
arr[arr<=6]

array([1, 2, 3, 4, 5, 6])

In [95]:
arr=np.arange(0,10)

In [96]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
1/arr

C:\Users\hadah\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [98]:
arr/arr

C:\Users\hadah\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [99]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [100]:
np.log(arr)

C:\Users\hadah\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [101]:
    arr.sum()

45

In [102]:
arr.mean()

4.5

In [108]:
arr_2dw=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [109]:
arr_2dw

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
arr_2dw.shape

(3, 4)

In [112]:
arr_2dw.sum()

78

In [113]:
arr_2dw.sum(axis=0)

array([15, 18, 21, 24])

In [114]:
arr_2dw.sum(axis=1)

array([10, 26, 42])